@startuml
left to right direction

actor "Usuari Generic" as generic_user
actor "Usuari Tutor" as tutor_user
tutor_user -|> generic_user

usecase "Login" as UC1
usecase "Consulta Child" as UC2

generic_user --> UC1
tutor_user --> UC2

@enduml
