graph TD;
    A[Benvinguda] --> B[Login]
    B --> C[List Childs]
    C --> D[Child]
    B --> D
    B --> E[Registre User/Child]
    B --> F[Forgot Pass]
    D --> G[Cuidador Add / Modify / Remove]
    D --> H[Editar Perfil]
    D --> I[Editar Child]